// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAPI = "apis"

// API mapped from table <apis>
type API struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Method    string         `gorm:"column:method;type:varchar(20);comment:'请求方式'" json:"method"`     // '请求方式'
	Path      string         `gorm:"column:path;type:varchar(100);comment:'访问路径'" json:"path"`        // '访问路径'
	Category  string         `gorm:"column:category;type:varchar(50);comment:'所属类别'" json:"category"` // '所属类别'
	Desc      string         `gorm:"column:desc;type:varchar(100);comment:'说明'" json:"desc"`          // '说明'
	Creator   string         `gorm:"column:creator;type:varchar(20);comment:'创建人'" json:"creator"`    // '创建人'
}

// TableName API's table name
func (*API) TableName() string {
	return TableNameAPI
}
