// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLiveDetail = "live_details"

// LiveDetail 直播间详情表
type LiveDetail struct {
	LiveRoomID    int64  `gorm:"column:live_room_id;type:bigint(20);primaryKey;comment:直播间ID，主键" json:"liveRoomId"`           // 直播间ID，主键
	LiveTitle     string `gorm:"column:live_title;type:varchar(255);not null;comment:直播标题" json:"liveTitle"`                  // 直播标题
	LiveStartTime int64  `gorm:"column:live_start_time;type:bigint(20);not null;comment:开播时间（Unix 时间戳）" json:"liveStartTime"` // 开播时间（Unix 时间戳）
	HostID        int64  `gorm:"column:host_id;type:bigint(20);not null;comment:主播ID，用于关联主播" json:"hostId"`                   // 主播ID，用于关联主播
	CreatedAt     int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                             // 创建时间（Unix 时间戳)
}

// TableName LiveDetail's table name
func (*LiveDetail) TableName() string {
	return TableNameLiveDetail
}
