// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMenu = "menus"

// Menu mapped from table <menus>
type Menu struct {
	ID         int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Name       string         `gorm:"column:name;type:varchar(50);comment:'菜单名称(英文名, 可用于国际化)'" json:"name"`                                 // '菜单名称(英文名, 可用于国际化)'
	Title      string         `gorm:"column:title;type:varchar(50);comment:'菜单标题(无法国际化时使用)'" json:"title"`                                  // '菜单标题(无法国际化时使用)'
	Icon       string         `gorm:"column:icon;type:varchar(50);comment:'菜单图标'" json:"icon"`                                              // '菜单图标'
	Path       string         `gorm:"column:path;type:varchar(100);comment:'菜单访问路径'" json:"path"`                                           // '菜单访问路径'
	Redirect   string         `gorm:"column:redirect;type:varchar(100);comment:'重定向路径'" json:"redirect"`                                    // '重定向路径'
	Component  string         `gorm:"column:component;type:varchar(100);comment:'前端组件路径'" json:"component"`                                 // '前端组件路径'
	Sort       int64          `gorm:"column:sort;type:int(3) unsigned;default:999;comment:'菜单顺序(1-999)'" json:"sort"`                       // '菜单顺序(1-999)'
	Status     int64          `gorm:"column:status;type:tinyint(1);default:1;comment:'菜单状态(正常/禁用, 默认正常)'" json:"status"`                    // '菜单状态(正常/禁用, 默认正常)'
	Hidden     int64          `gorm:"column:hidden;type:tinyint(1);default:2;comment:'菜单在侧边栏隐藏(1隐藏，2显示)'" json:"hidden"`                    // '菜单在侧边栏隐藏(1隐藏，2显示)'
	NoCache    int64          `gorm:"column:no_cache;type:tinyint(1);default:2;comment:'菜单是否被 <keep-alive> 缓存(1不缓存，2缓存)'" json:"noCache"`   // '菜单是否被 <keep-alive> 缓存(1不缓存，2缓存)'
	AlwaysShow int64          `gorm:"column:always_show;type:tinyint(1);default:2;comment:'忽略之前定义的规则，一直显示根路由(1忽略，2不忽略)'" json:"alwaysShow"` // '忽略之前定义的规则，一直显示根路由(1忽略，2不忽略)'
	Breadcrumb int64          `gorm:"column:breadcrumb;type:tinyint(1);default:1;comment:'面包屑可见性(可见/隐藏, 默认可见)'" json:"breadcrumb"`          // '面包屑可见性(可见/隐藏, 默认可见)'
	ActiveMenu string         `gorm:"column:active_menu;type:varchar(100);comment:'在其它路由时，想在侧边栏高亮的路由'" json:"activeMenu"`                   // '在其它路由时，想在侧边栏高亮的路由'
	ParentID   int64          `gorm:"column:parent_id;type:bigint(20) unsigned;comment:'父菜单编号(编号为0时表示根菜单)'" json:"parentId"`                // '父菜单编号(编号为0时表示根菜单)'
	Creator    string         `gorm:"column:creator;type:varchar(20);comment:'创建人'" json:"creator"`                                         // '创建人'
	Children   []*Menu        `gorm:"-" json:"children"`                                                                                    // 子菜单集合
	Roles      []*Role        `gorm:"many2many:role_menus;" json:"roles"`                                                                   // 角色菜单多对多关系
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
