// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperationLog = "operation_logs"

// OperationLog mapped from table <operation_logs>
type OperationLog struct {
	ID         int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Username   string         `gorm:"column:username;type:varchar(20);comment:'用户登录名'" json:"username"`      // '用户登录名'
	IP         string         `gorm:"column:ip;type:varchar(20);comment:'Ip地址'" json:"ip"`                   // 'Ip地址'
	IPLocation string         `gorm:"column:ip_location;type:varchar(20);comment:'Ip所在地'" json:"ipLocation"` // 'Ip所在地'
	Method     string         `gorm:"column:method;type:varchar(20);comment:'请求方式'" json:"method"`           // '请求方式'
	Path       string         `gorm:"column:path;type:varchar(100);comment:'访问路径'" json:"path"`              // '访问路径'
	Desc       string         `gorm:"column:desc;type:varchar(100);comment:'说明'" json:"desc"`                // '说明'
	Status     int64          `gorm:"column:status;type:int(4);comment:'响应状态码'" json:"status"`               // '响应状态码'
	StartTime  time.Time      `gorm:"column:start_time;type:datetime(3);comment:'发起时间'" json:"startTime"`    // '发起时间'
	TimeCost   int64          `gorm:"column:time_cost;type:int(6);comment:'请求耗时(ms)'" json:"timeCost"`       // '请求耗时(ms)'
	UserAgent  string         `gorm:"column:user_agent;type:varchar(20);comment:'浏览器标识'" json:"userAgent"`   // '浏览器标识'
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
