// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePauseRecord = "pause_records"

// PauseRecord 暂停记录表
type PauseRecord struct {
	ID         int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"` // 主键ID
	LiveDataID int64  `gorm:"column:live_data_id;type:bigint(20);not null;comment:直播数据表的ID，用于关联" json:"liveDataId"`  // 直播数据表的ID，用于关联
	HostID     int64  `gorm:"column:host_id;type:bigint(20);not null;comment:主播ID，用于关联" json:"hostId"`               // 主播ID，用于关联
	PauseTime  int64  `gorm:"column:pause_time;type:bigint(20);not null;comment:暂停时间（Unix 时间戳）" json:"pauseTime"`    // 暂停时间（Unix 时间戳）
	ResumeTime int64  `gorm:"column:resume_time;type:bigint(20);not null;comment:恢复时间（Unix 时间戳）" json:"resumeTime"`  // 恢复时间（Unix 时间戳）
	Duration   int64  `gorm:"column:duration;type:int(11);not null;comment:暂停时长，以分钟为单位" json:"duration"`             // 暂停时长，以分钟为单位
	Reason     string `gorm:"column:reason;type:text;not null;comment:暂停理由" json:"reason"`                           // 暂停理由
	CreatedAt  int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                       // 创建时间（Unix 时间戳）
}

// TableName PauseRecord's table name
func (*PauseRecord) TableName() string {
	return TableNamePauseRecord
}
