// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"-"`
	Name      string         `gorm:"column:name;type:varchar(20);not null" json:"name"`
	Keyword   string         `gorm:"column:keyword;type:varchar(20);not null" json:"keyword"`
	Desc      string         `gorm:"column:desc;type:varchar(100)" json:"desc"`
	Status    int64          `gorm:"column:status;type:tinyint(1);default:1;comment:'1正常, 2禁用'" json:"status"`                                          // '1正常, 2禁用'
	Sort      int64          `gorm:"column:sort;type:int(3);default:999;comment:'角色排序(排序越大权限越低, 不能查看比自己序号小的角色, 不能编辑同序号用户权限, 排序为1表示超级管理员)'" json:"sort"` // '角色排序(排序越大权限越低, 不能查看比自己序号小的角色, 不能编辑同序号用户权限, 排序为1表示超级管理员)'
	Creator   string         `gorm:"column:creator;type:varchar(20)" json:"creator"`
	Users     []*User        `gorm:"many2many:user_roles" json:"users"`
	Menus     []*Menu        `gorm:"many2many:role_menus;" json:"menus"` // 角色菜单多对多关系
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
