// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleMenu = "role_menus"

// RoleMenu mapped from table <role_menus>
type RoleMenu struct {
	MenuID int64 `gorm:"column:menu_id;type:bigint(20) unsigned;primaryKey" json:"menuId"`
	RoleID int64 `gorm:"column:role_id;type:bigint(20) unsigned;primaryKey" json:"roleId"`
}

// TableName RoleMenu's table name
func (*RoleMenu) TableName() string {
	return TableNameRoleMenu
}
