// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSuperAdmin = "super_admins"

// SuperAdmin 超级管理员表
type SuperAdmin struct {
	ID        int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"`         // 主键ID
	Username  string `gorm:"column:username;type:varchar(50);not null;comment:用户名，唯一" json:"username"`                      // 用户名，唯一
	Password  string `gorm:"column:password;type:varchar(255);not null;comment:密码（建议加密存储）" json:"password"`                 // 密码（建议加密存储）
	Nickname  string `gorm:"column:nickname;type:varchar(50);not null;comment:昵称" json:"nickname"`                          // 昵称
	Phone     string `gorm:"column:phone;type:varchar(15);comment:手机号码" json:"phone"`                                       // 手机号码
	Status    string `gorm:"column:status;type:enum('active','inactive');not null;default:active;comment:状态" json:"status"` // 状态
	CreatedAt int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                               // 创建时间（Unix 时间戳）
	UpdatedAt int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                               // 修改时间（Unix 时间戳）
}

// TableName SuperAdmin's table name
func (*SuperAdmin) TableName() string {
	return TableNameSuperAdmin
}
