// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	RoleID int64 `gorm:"column:role_id;type:bigint(20) unsigned;primaryKey" json:"roleId"`
	UserID int64 `gorm:"column:user_id;type:bigint(20) unsigned;primaryKey" json:"userId"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
