// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameViolation = "violations"

// Violation 违规记录表
type Violation struct {
	ID                  int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键ID" json:"id,string"`                                    // 主键ID
	HostNickname        string `gorm:"column:host_nickname;type:varchar(50);not null;comment:主播昵称" json:"hostNickname"`                                          // 主播昵称
	HostID              int64  `gorm:"column:host_id;type:bigint(20);not null;comment:主播ID" json:"hostId"`                                                       // 主播ID
	SecurityCode        string `gorm:"column:security_code;type:varchar(50);not null;comment:安全码" json:"securityCode"`                                           // 安全码
	AccountStatus       string `gorm:"column:account_status;type:enum('active','suspended','banned');not null;default:active;comment:账号状态" json:"accountStatus"` // 账号状态
	ViolationNumber     string `gorm:"column:violation_number;type:varchar(50);not null;comment:违规编号" json:"violationNumber"`                                    // 违规编号
	ViolationTime       int64  `gorm:"column:violation_time;type:bigint(20);not null;comment:违规时间（Unix 时间戳）" json:"violationTime"`                               // 违规时间（Unix 时间戳）
	ViolationReason     string `gorm:"column:violation_reason;type:text;not null;comment:违规原因" json:"violationReason"`                                           // 违规原因
	ViolationImpact     string `gorm:"column:violation_impact;type:text;not null;comment:违规影响" json:"violationImpact"`                                           // 违规影响
	ViolationLiveRoomID string `gorm:"column:violation_live_room_id;type:varchar(100);not null;comment:违规对象是直播间的ID" json:"violationLiveRoomId"`                  // 违规对象是直播间的ID
	CreatedAt           int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                                          // 创建时间（Unix 时间戳）
}

// TableName Violation's table name
func (*Violation) TableName() string {
	return TableNameViolation
}
