// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"demo20220320/model"
)

func newHost(db *gorm.DB, opts ...gen.DOOption) host {
	_host := host{}

	_host.hostDo.UseDB(db, opts...)
	_host.hostDo.UseModel(&model.Host{})

	tableName := _host.hostDo.TableName()
	_host.ALL = field.NewAsterisk(tableName)
	_host.ID = field.NewInt64(tableName, "id")
	_host.Username = field.NewString(tableName, "username")
	_host.Password = field.NewString(tableName, "password")
	_host.Nickname = field.NewString(tableName, "nickname")
	_host.Phone = field.NewString(tableName, "phone")
	_host.Email = field.NewString(tableName, "email")
	_host.ProfilePicture = field.NewString(tableName, "profile_picture")
	_host.Bio = field.NewString(tableName, "bio")
	_host.FollowersCount = field.NewInt64(tableName, "followers_count")
	_host.CreatedAt = field.NewInt64(tableName, "created_at")
	_host.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_host.fillFieldMap()

	return _host
}

// host 主播基础信息表
type host struct {
	hostDo

	ALL            field.Asterisk
	ID             field.Int64
	Username       field.String // 用户名
	Password       field.String // 密码（建议加密存储）
	Nickname       field.String // 昵称
	Phone          field.String // 手机号码
	Email          field.String // 电子邮件
	ProfilePicture field.String // 头像URL
	Bio            field.String // 个人简介
	FollowersCount field.Int64  // 粉丝数量
	CreatedAt      field.Int64  // 创建时间（Unix 时间戳）
	UpdatedAt      field.Int64  // 更新时间（Unix 时间戳）

	fieldMap map[string]field.Expr
}

func (h host) Table(newTableName string) *host {
	h.hostDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h host) As(alias string) *host {
	h.hostDo.DO = *(h.hostDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *host) updateTableName(table string) *host {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Username = field.NewString(table, "username")
	h.Password = field.NewString(table, "password")
	h.Nickname = field.NewString(table, "nickname")
	h.Phone = field.NewString(table, "phone")
	h.Email = field.NewString(table, "email")
	h.ProfilePicture = field.NewString(table, "profile_picture")
	h.Bio = field.NewString(table, "bio")
	h.FollowersCount = field.NewInt64(table, "followers_count")
	h.CreatedAt = field.NewInt64(table, "created_at")
	h.UpdatedAt = field.NewInt64(table, "updated_at")

	h.fillFieldMap()

	return h
}

func (h *host) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *host) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 11)
	h.fieldMap["id"] = h.ID
	h.fieldMap["username"] = h.Username
	h.fieldMap["password"] = h.Password
	h.fieldMap["nickname"] = h.Nickname
	h.fieldMap["phone"] = h.Phone
	h.fieldMap["email"] = h.Email
	h.fieldMap["profile_picture"] = h.ProfilePicture
	h.fieldMap["bio"] = h.Bio
	h.fieldMap["followers_count"] = h.FollowersCount
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
}

func (h host) clone(db *gorm.DB) host {
	h.hostDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h host) replaceDB(db *gorm.DB) host {
	h.hostDo.ReplaceDB(db)
	return h
}

type hostDo struct{ gen.DO }

type IHostDo interface {
	gen.SubQuery
	Debug() IHostDo
	WithContext(ctx context.Context) IHostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHostDo
	WriteDB() IHostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHostDo
	Not(conds ...gen.Condition) IHostDo
	Or(conds ...gen.Condition) IHostDo
	Select(conds ...field.Expr) IHostDo
	Where(conds ...gen.Condition) IHostDo
	Order(conds ...field.Expr) IHostDo
	Distinct(cols ...field.Expr) IHostDo
	Omit(cols ...field.Expr) IHostDo
	Join(table schema.Tabler, on ...field.Expr) IHostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHostDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHostDo
	Group(cols ...field.Expr) IHostDo
	Having(conds ...gen.Condition) IHostDo
	Limit(limit int) IHostDo
	Offset(offset int) IHostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHostDo
	Unscoped() IHostDo
	Create(values ...*model.Host) error
	CreateInBatches(values []*model.Host, batchSize int) error
	Save(values ...*model.Host) error
	First() (*model.Host, error)
	Take() (*model.Host, error)
	Last() (*model.Host, error)
	Find() ([]*model.Host, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Host, err error)
	FindInBatches(result *[]*model.Host, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Host) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHostDo
	Assign(attrs ...field.AssignExpr) IHostDo
	Joins(fields ...field.RelationField) IHostDo
	Preload(fields ...field.RelationField) IHostDo
	FirstOrInit() (*model.Host, error)
	FirstOrCreate() (*model.Host, error)
	FindByPage(offset int, limit int) (result []*model.Host, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hostDo) Debug() IHostDo {
	return h.withDO(h.DO.Debug())
}

func (h hostDo) WithContext(ctx context.Context) IHostDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hostDo) ReadDB() IHostDo {
	return h.Clauses(dbresolver.Read)
}

func (h hostDo) WriteDB() IHostDo {
	return h.Clauses(dbresolver.Write)
}

func (h hostDo) Session(config *gorm.Session) IHostDo {
	return h.withDO(h.DO.Session(config))
}

func (h hostDo) Clauses(conds ...clause.Expression) IHostDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hostDo) Returning(value interface{}, columns ...string) IHostDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hostDo) Not(conds ...gen.Condition) IHostDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hostDo) Or(conds ...gen.Condition) IHostDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hostDo) Select(conds ...field.Expr) IHostDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hostDo) Where(conds ...gen.Condition) IHostDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hostDo) Order(conds ...field.Expr) IHostDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hostDo) Distinct(cols ...field.Expr) IHostDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hostDo) Omit(cols ...field.Expr) IHostDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hostDo) Join(table schema.Tabler, on ...field.Expr) IHostDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hostDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHostDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hostDo) RightJoin(table schema.Tabler, on ...field.Expr) IHostDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hostDo) Group(cols ...field.Expr) IHostDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hostDo) Having(conds ...gen.Condition) IHostDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hostDo) Limit(limit int) IHostDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hostDo) Offset(offset int) IHostDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHostDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hostDo) Unscoped() IHostDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hostDo) Create(values ...*model.Host) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hostDo) CreateInBatches(values []*model.Host, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hostDo) Save(values ...*model.Host) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hostDo) First() (*model.Host, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Host), nil
	}
}

func (h hostDo) Take() (*model.Host, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Host), nil
	}
}

func (h hostDo) Last() (*model.Host, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Host), nil
	}
}

func (h hostDo) Find() ([]*model.Host, error) {
	result, err := h.DO.Find()
	return result.([]*model.Host), err
}

func (h hostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Host, err error) {
	buf := make([]*model.Host, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hostDo) FindInBatches(result *[]*model.Host, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hostDo) Attrs(attrs ...field.AssignExpr) IHostDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hostDo) Assign(attrs ...field.AssignExpr) IHostDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hostDo) Joins(fields ...field.RelationField) IHostDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hostDo) Preload(fields ...field.RelationField) IHostDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hostDo) FirstOrInit() (*model.Host, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Host), nil
	}
}

func (h hostDo) FirstOrCreate() (*model.Host, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Host), nil
	}
}

func (h hostDo) FindByPage(offset int, limit int) (result []*model.Host, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hostDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hostDo) Delete(models ...*model.Host) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hostDo) withDO(do gen.Dao) *hostDo {
	h.DO = *do.(*gen.DO)
	return h
}
